### ISSUE TITLE
Error on interface Card

### ISSUE THREAD

**Issue by ghost** [mrphu3074/typed-native-base#1]
Hello @mrphu3074 

First of all, thanks for the initiative to develop this work.

I've got the error on interface Card:

`
typings\globals\native-base\index.d.ts(238,15): error TS2430: Interface 'Card' incorrectly extends interface 'ListViewProperties'.
  Types of property 'ref' are incompatible.
    Type 'Ref<ViewProperties & ListViewProperties>' is not assignable to type 'Ref<this>'.
      Type '(instance: ViewProperties & ListViewProperties) => any' is not assignable to type 'Ref<this>'.
        Type '(instance: ViewProperties & ListViewProperties) => any' is not assignable to type '(instance: ListViewStatic & ScrollViewStatic & ViewStatic) => any'.
          Types of parameters 'instance' and 'instance' are incompatible.
            Type 'ListViewStatic & ScrollViewStatic & ViewStatic' is not assignable to type 'ViewProperties & ListViewProperties'.
              Type 'ListViewStatic & ScrollViewStatic & ViewStatic' is not assignable to type 'ListViewProperties'.
                Property 'dataSource' is missing in type 'ListViewStatic & ScrollViewStatic & ViewStatic'.
typings\globals\native-base\index.d.ts(238,15): error TS2430: Interface 'Card' incorrectly extends interface 'ViewProperties'.
  Types of property 'ref' are incompatible.
    Type 'Ref<ViewProperties & ListViewProperties>' is not assignable to type 'Ref<ViewStatic, this>'.
      Type '(instance: ViewProperties & ListViewProperties) => any' is not assignable to type 'Ref<ViewStatic, this>'.
        Type '(instance: ViewProperties & ListViewProperties) => any' is not assignable to type '(instance: ViewStatic) => any'.
          Types of parameters 'instance' and 'instance' are incompatible.
            Type 'ViewStatic' is not assignable to type 'ViewProperties & ListViewProperties'.
              Type 'ViewStatic' is not assignable to type 'ListViewProperties'.
                Property 'dataSource' is missing in type 'ViewStatic'.
`

I think that something has change on react-native typings and the typed-native-base is outdated. If it's true, how can I fix this? I wanted to suggest some fix but I am a newbie in TS. :(

That's all, and sorry for the English skills. :)

**Comment by mrphu3074** [comment]
Hi, 
Thanks for contributing, Can you show me how you install it and what editor that you using ?

Thanks

**Comment by mrphu3074** [comment]
@dougefr i just fixed it.

Please install with latest commit code.

`typings install --save --global github:mrphu3074/typed-native-base#fc659726daf0595a52ae267ca4c928242ee01c6e`

**Comment by ghost** [comment]
Thanks a lot @mrphu3074 ! Now it's working! :)
