### ISSUE TITLE
How is the file generated?

### ISSUE THREAD

**Issue by wcandillon** [mrphu3074/typed-native-base#3]
@mrphu3074 In the `index.d.ts` file it is writte:

```
// Generated by typings
```

How is this file generated? I'm asking because I would like to add the declaration of FooterTab in it.

**Comment by mrphu3074** [comment]
Don't worry, I copied from a template. 😄  . Feel free to add more declaration.

**Comment by wcandillon** [comment]
@mrphu3074 great to know! thks a lot!
